---
title: "Data Wrangling I"
author: "Diana Hernandez"
date: "2023-09-19"
output: github_document
---

```{r}
library(tidyverse)
```

Let's import the 'FAS__litters.csv' csv using a relative path.

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")

litters_df = 
  janitor:: clean_names(litters_df)

```

Let's import the 'FAS__pups.csv' csv using a relative path.

```{r}
pups_df =
  read_csv("data/FAS_pups.csv")

pups_df = 
  janitor:: clean_names(pups_df)

```

## Look at data

```{r}
litters_df

head(litters_df)

tail(litters_df)
```

You can use view to see entire dataset. Use eval = FALSE 

```{r eval = FALSE}
view(litters_df)
```

Look at data summary

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in 'read_*'. Use skip when rows do not have actual data

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 10, col_names = FALSE)
```

Look at NA values. 
```{r}
litters_df =
  read_csv(
    "data/FAS_litters.csv",
    na = c("NA", 19))
```

Column types

```{r}
litters_df =
  read_csv(
    "data/FAS_litters.csv",
    col_types =
      col(
        'GD0 Weight' = col_character()
      )
```

